from typing import List, Dict
from mem0 import MemoryClient
from cred import MEM0_API_KEY

mem0 = MemoryClient(api_key=MEM0_API_KEY)

def retrieve_context(query: str, user_id: str) -> List[Dict]:
    """
    Summary:
        Searches Mem0 for memories matching the provided query and user_id,
        concatenates the results, and returns them in a format suitable for 
        system context.

    Args:
        query (str): The search string to find relevant memories.
        user_id (str): Unique identifier for the user whose memories are searched.

    Returns:
        List[Dict]: 
            - A list containing a single dictionary with:
                - "role": always "system"
                - "content": concatenated relevant memory text
            - Returns an empty list if no relevant memories are found.
    """
    try:
        memories = mem0.search(
            query = query, 
            filters = {"user_id" : user_id},

            )
        
        memory_list = memories.get("results", [])

        serialized = " ".join(mem["memory"] for mem in memory_list)

        if not serialized:
            return[]

        return [{
            "role": "system",
            "content": f"Relevant information: {serialized}"
        }]
    except Exception as e:
        print("Memory retrieval error:", e)
        return []

def save_interaction(user_id: str, user_input: str, assistant_response: str):
    """
    Summary:
        Stores both the user's input and the assistant's response in Mem0 
        for future retrieval.

    Args:
        user_id (str): Unique identifier for the user.
        user_input (str): The message or query sent by the user.
        assistant_response (str): The response generated by the assistant.

    Returns:
        None
    """
    try:
        mem0.add(
            [
                {"role": "user", "content": user_input},
                {"role": "assistant", "content": assistant_response}
            ],
            user_id=user_id
        )
    except Exception as e:
        print("Memory save error:", e)  