from config import get_llm
from prompts import get_prompt

llm = get_llm()
prompt = get_prompt()

def generate_response(user_input: str, context):
    """
    Summary:
        This function uses a prompt and a language model (LLM) to generate
        a conversational response.

    Args:
        user_input (str): The message or query from the user.
        context (any): Relevant context or history to provide additional
                       information for generating a more accurate response.

    Returns:
        str: The text content of the response generated by the language model.
    """
    chain = prompt | llm
    response = chain.invoke({
        "input": user_input,
        "context": context
    })
    return response.content[0]['text']